language: python
python:
- '3.6'
- '3.7'
install:
- python setup.py install
script:
- pytest aldy --solvers=cbc
deploy:
  provider: pypi
  user: inumanag
  password:
    secure: nqDCvglGo5X9G6fxf3MbwebypSDZNskKOSfFPa4V8t7fp530Z4dIi6GPIFfMYqTIrAy+7xeT33h2th/R9eXa5nllUMM/NK9HKPtru/hgv7NPCPLhuwGbglty8UTUB8nrZ2oZlFd6M7/Qh1pnSEjaSxSTYj5GdegQGddObVZK7pNP2YEQUW9Strax06PGgSYUrfhS1ZuW16P9jn0jfG8b2zKdviwepePVMzl3pmc+z9xFnIhsT7HrU3IC4mpz+2F94Zl7+X46djZjL/jD7qIyeA2nrnEOW29YTkLpqol31M7HhDc1grweEgl2JRmNhweZkGNgWwV0VXYrWPgMACBxS7VB2QCx2IrfCGxZg1j2bEZuSftZYuZh2E/1IBsBbNvW+NA6+ncjCZ1V7vDIJfqnh/ZSdz0o/0JbTHE1WQAUTXGLgmG3f+11qFNfvi8NtbOE6/BUoWmNlrW21Tmqa6D7HECBDIj/w8qO/HsJF+jIrQodx9zulwmZBesUzorOPLxnWwB95ooRbW+QrnjV4ApdJDGI51natml4Mx4Hhmw3Jg9XcCiGu2vbZ5KH/CSAPWmL6E9V3IA5m6sGrfhFj+SM8riOogspuErU0MJYqnU76z7Xo20qFeyG5dowo20szzKPmNGrfM/c9hDINZB8Febpxu7VZsee5JFHiWS+1U+ViVQ=
